trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '16.x'
    displayName: 'Install Node.js'

  - task: npm@1
    inputs:
      command: 'install'
    displayName: 'npm install'

  - task: npm@1
    inputs:
      command: 'build'
    displayName: 'npm build'
